#################################################################################
##################################################################################
##    Copyright (C) 2019-present Prominic.NET, Inc.                             ##
##                                                                              ##
##    This program is free software: you can redistribute it and/or modify      ##
##    it under the terms of the Server Side Public License, version 1,          ##
##    as published by MongoDB, Inc.                                             ##
##                                                                              ##
##    This program is distributed in the hope that it will be useful,           ##
##    but WITHOUT ANY WARRANTY; without even the implied warranty of            ##
##    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             ##
##    Server Side Public License for more details.                              ##
##                                                                              ##
##    You should have received a copy of the Server Side Public License         ##
##    along with this program. If not, see:                                     ##
##                                                                              ##
##    http://www.mongodb.com/licensing/server-side-public-license               ##
##                                                                              ##
##    As a special exception, the copyright holders give permission to link the ##
##    code of portions of this program with the OpenSSL library under certain   ##
##    conditions as described in each individual source file and distribute     ##
##    linked combinations including the program with the OpenSSL library. You   ##
##    must comply with the Server Side Public License in all respects for       ##
##    all of the code used other than as permitted herein. If you modify file(s)##
##    with this exception, you may extend this exception to your version of the ##
##    file(s), but you are not obligated to do so. If you do not wish to do so, ##
##    delete this exception statement from your version. If you delete this     ##
##    exception statement from all source files in the program, then also delete##
##    it in the license file.                                                   ##
##################################################################################
##################################################################################
--- 
hosts: 
  - 
    run_letsencrypt: false
    autostart: true
    box: Makr44/Docova-Ubuntu-18.04
    client_directory: client_directory
    client_id: client_id
    client_secret: client_secret
    database_name: docova_db
    database_password: password12
    database_user: docova_db_user
    document_root: "/var/docova/attachments"
    gateway: "192.168.2.1"
    google_api_key: google_api_key
    identifier: acme.docova.m4kr.net
    ip: "192.168.2.163"
    ldap_adkey: ~
    ldap_domain: ~
    ldap_groupkey: ~
    ldap_password: ~
    ldap_username: ~
    mac: 525400c9c010
    mailer_password: mailer_password
    mailer_user: mark.gilbert@prominic.net
    mysql_root_password: mysql_root_password
    name: acme_docova
    netmask: "255.255.255.0"
    sender_address: sender_address@sender_address.net
    weather_api_key: weather_api_key
    folders: 
      - 
        map: ./conf
        to: /vagrant
    provider: 
      - 
        directive: memory
        value: "4096"
      - 
        directive: cpus
        value: "2"
    provision: 
      - ./scripts/aliases.sh
path: "."
